// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelGwMckqQJVYI6RSbLwhxn6FgR_VGBYc',
    appId: '1:101100907568:web:c473664b52bc39eeb911f5',
    messagingSenderId: '101100907568',
    projectId: 'nova-87b9a',
    authDomain: 'nova-87b9a.firebaseapp.com',
    storageBucket: 'nova-87b9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvZMVAbTzXmWulBx43_L1m59c6zp408DI',
    appId: '1:1029448023182:android:4d3673140b94a65f885ddf',
    messagingSenderId: '1029448023182',
    projectId: 'aruuu-d0881',
    databaseURL: 'https://aruuu-d0881-default-rtdb.firebaseio.com',
    storageBucket: 'aruuu-d0881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDffwBdRsB93C_slpWImp8WRNdGY1l71ck',
    appId: '1:1029448023182:ios:be6ecd9a3c6efec6885ddf',
    messagingSenderId: '1029448023182',
    projectId: 'aruuu-d0881',
    databaseURL: 'https://aruuu-d0881-default-rtdb.firebaseio.com',
    storageBucket: 'aruuu-d0881.firebasestorage.app',
    androidClientId: '1029448023182-7sl88a29v8r7s24leqhc5vjo4i8mi0go.apps.googleusercontent.com',
    iosClientId: '1029448023182-ecr1s3d50qramjl7osv59re53eh96lrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.stiky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpTI5podAMTzl6Qw0vRI5mkm5_Qf6XQo',
    appId: '1:101100907568:ios:041fe76f8f00ef48b911f5',
    messagingSenderId: '101100907568',
    projectId: 'nova-87b9a',
    storageBucket: 'nova-87b9a.firebasestorage.app',
    iosBundleId: 'com.example.stiky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDelGwMckqQJVYI6RSbLwhxn6FgR_VGBYc',
    appId: '1:101100907568:web:f6543374857fd1a9b911f5',
    messagingSenderId: '101100907568',
    projectId: 'nova-87b9a',
    authDomain: 'nova-87b9a.firebaseapp.com',
    storageBucket: 'nova-87b9a.firebasestorage.app',
  );

}