import 'package:stiky/data/university/localized_string.dart';
import 'package:stiky/data/university/university_model.dart';

/// Учебные заведения Алматы для заливки в Firestore.
///
/// Залить один раз:
/// ```dart
/// await context.read<UniversityRepository>().seedAll(kSeedUniversities);
/// ```
const List<University> kSeedUniversities = [
  University(
    id: 'kimep',
    name: LocalizedString(
      ru: 'KIMEP University',
      en: 'KIMEP University',
      kk: 'KIMEP Университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'KIMEP University — один из ведущих частных университетов Казахстана с обучением на английском языке. Специализируется на бизнесе, праве и социальных науках. Аккредитован AACSB.',
      en: 'KIMEP University is one of Kazakhstan\'s leading private universities with English-medium instruction. Specializes in business, law and social sciences. AACSB accredited.',
      kk: 'KIMEP University — Қазақстанның жетекші жеке университеттерінің бірі, ағылшын тілінде оқытады. Бизнес, құқық және әлеуметтік ғылымдарға маманданған. AACSB аккредитациясы бар.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Бизнес', 'Право', 'Социальные науки', 'Медиа'],
    costRange: '2 800 000 – 3 800 000 ₸/год',
    duration: '4 года',
    languages: ['Английский'],
    format: 'Очная',
    website: 'https://www.kimep.kz',
    instagram: 'https://instagram.com/kimepuniversity',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kimep.kz',
    phone: '+7 727 270 42 13',
    tags: ['business', 'law', 'bachelor', 'master'],
    minEnt: 80,
    minIelts: 6.0,
  ),
  University(
    id: 'kbtu',
    name: LocalizedString(
      ru: 'Казахстанско-Британский технический университет',
      en: 'Kazakhstan-British Technical University',
      kk: 'Қазақстан-Британ техникалық университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КБТУ — ведущий технический университет с совместными программами британских вузов. Сильные направления: нефтегазовая инженерия, IT, бизнес.',
      en: 'KBTU is a leading technical university with joint programs from British universities. Strong areas: oil and gas engineering, IT, business.',
      kk: 'ҚБТУ — британдық университеттермен бірлескен бағдарламалары бар жетекші техникалық университет. Мұнай-газ инженериясы, IT, бизнес — күшті бағыттар.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    directions: ['IT', 'Инженерия', 'Нефтегазовая отрасль', 'Бизнес'],
    costRange: '2 200 000 – 3 500 000 ₸/год',
    duration: '4 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная',
    website: 'https://kbtu.kz',
    instagram: 'https://instagram.com/kbtu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kbtu.kz',
    phone: '+7 (727) 272-42-93',
    tags: ['it', 'engineering', 'business', 'bachelor', 'master'],
    minEnt: 70,
    minIelts: 5.5,
  ),
  University(
    id: 'kaznu',
    name: LocalizedString(
      ru: 'Казахский национальный университет им. аль-Фараби',
      en: 'Al-Farabi Kazakh National University',
      kk: 'Әл-Фараби атындағы Қазақ ұлттық университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КазНУ — крупнейший и старейший университет Казахстана. Более 100 специальностей. Есть бюджетные места по государственному гранту.',
      en: 'KazNU is the largest and oldest university in Kazakhstan. Over 100 majors. State grant places available.',
      kk: 'ҚазҰУ — Қазақстанның ең ірі және көне университеті. 100-ден астам мамандық. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    directions: ['IT', 'Медицина', 'Право', 'Бизнес', 'Инженерия', 'Гуманитарные науки', 'Естественные науки'],
    costRange: 'Грант / до 1 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Дистанционная',
    website: 'https://kaznu.kz',
    instagram: 'https://instagram.com/kaznu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'priem@kaznu.kz',
    phone: '+7 (727) 377-33-33',
    tags: ['it', 'medicine', 'law', 'business', 'engineering', 'grants', 'bachelor', 'master'],
    minEnt: 65,
  ),
  University(
    id: 'iitu',
    name: LocalizedString(
      ru: 'Международный университет информационных технологий',
      en: 'International University of Information Technology',
      kk: 'Халықаралық ақпараттық технологиялар университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'МУИТ — ведущий IT-университет Казахстана. Готовит специалистов в области программной инженерии, кибербезопасности и ИИ. Есть государственные гранты.',
      en: 'IITU is Kazakhstan\'s leading IT university. Trains specialists in software engineering, cybersecurity and AI. State grants available.',
      kk: 'ХАТУ — Қазақстанның жетекші IT-университеті. Бағдарламалық инженерия, киберқауіпсіздік және ЖИ мамандарын дайындайды. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    directions: ['IT'],
    costRange: 'Грант / до 1 600 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная',
    website: 'https://iitu.edu.kz',
    instagram: 'https://instagram.com/iitu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@iitu.edu.kz',
    phone: '+7 (727) 355-34-00',
    tags: ['it', 'engineering', 'grants', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'narxoz',
    name: LocalizedString(
      ru: 'Университет Нархоз',
      en: 'Narxoz University',
      kk: 'Нархоз Университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Нархоз — ведущий частный университет в области экономики и бизнеса. Международные аккредитации, партнёрство с European Business School.',
      en: 'Narxoz is a leading private university in economics and business. International accreditations, partnership with European Business School.',
      kk: 'Нархоз — экономика және бизнес саласындағы жетекші жеке университет. Халықаралық аккредитациялар, European Business School серіктестігі.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Бизнес', 'Право', 'Экономика', 'IT', 'Финансы'],
    costRange: '1 500 000 – 2 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Дистанционная',
    website: 'https://narxoz.kz',
    instagram: 'https://instagram.com/narxoz_university',
    imageUrl: '',
    logoUrl: '',
    email: 'admissions@narxoz.kz',
    phone: '+7 (727) 377-11-11',
    tags: ['business', 'law', 'it', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'kaznpu',
    name: LocalizedString(
      ru: 'КазНПУ им. Абая',
      en: 'Abai Kazakh National Pedagogical University',
      kk: 'Абай атындағы ҚазҰПУ',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Казахский национальный педагогический университет им. Абая — главный педагогический вуз Казахстана. Есть государственные гранты.',
      en: 'Abai KazNPU is Kazakhstan\'s main pedagogical university. State grants available.',
      kk: 'Абай атындағы ҚазҰПУ — Қазақстанның басты педагогикалық жоғары оқу орны. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    directions: ['Педагогика', 'Психология', 'Гуманитарные науки', 'Естественные науки', 'IT'],
    costRange: 'Грант / до 1 200 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная, Дистанционная',
    website: 'https://kaznpu.kz',
    instagram: 'https://instagram.com/kaznpu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kaznpu.kz',
    phone: '+7 (727) 291-91-91',
    tags: ['pedagogy', 'grants', 'bachelor', 'master'],
    minEnt: 55,
  ),
  University(
    id: 'kazmed',
    name: LocalizedString(
      ru: 'КазНМУ им. С. Д. Асфендиярова',
      en: 'S.D. Asfendiyarov Kazakh National Medical University',
      kk: 'С.Ж. Асфендияров атындағы ҚазҰМУ',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КазНМУ — ведущий медицинский вуз Казахстана. Готовит врачей, фармацевтов и специалистов общественного здравоохранения. Есть государственные гранты.',
      en: 'KazNMU is Kazakhstan\'s leading medical university. Trains doctors, pharmacists and public health specialists. State grants available.',
      kk: 'ҚазҰМУ — Қазақстанның жетекші медицина университеті. Дәрігерлер, фармацевттер және денсаулық сақтау мамандарын дайындайды. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Резидентура',
    directions: ['Медицина', 'Фармацевтика', 'Стоматология', 'Общественное здравоохранение'],
    costRange: 'Грант / до 2 000 000 ₸/год',
    duration: '5–6 лет',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная',
    website: 'https://kaznmu.kz',
    instagram: 'https://instagram.com/kaznmu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kaznmu.kz',
    phone: '+7 (727) 292-06-30',
    tags: ['medicine', 'grants', 'bachelor', 'master'],
    minEnt: 70,
  ),
  University(
    id: 'alma_u',
    name: LocalizedString(
      ru: 'Alma University',
      en: 'Alma University',
      kk: 'Alma University',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Alma University — современный частный университет с фокусом на бизнес, право и цифровые технологии.',
      en: 'Alma University is a modern private university focused on business, law and digital technologies.',
      kk: 'Alma University — бизнес, құқық және цифрлық технологияларға бағытталған заманауи жеке университет.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Бизнес', 'Право', 'IT', 'Дизайн'],
    costRange: '1 300 000 – 2 200 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Гибридная',
    website: 'https://alma.edu.kz',
    instagram: 'https://instagram.com/alma_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@alma.edu.kz',
    phone: '+7 (727) 311-11-40',
    tags: ['business', 'law', 'it', 'design', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'turan',
    name: LocalizedString(
      ru: 'Университет Туран',
      en: 'Turan University',
      kk: 'Тұран Университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Университет Туран — один из старейших частных университетов Казахстана. Широкий спектр направлений: экономика, IT, право, туризм и журналистика.',
      en: 'Turan University is one of the oldest private universities in Kazakhstan with a wide range of programs.',
      kk: 'Тұран университеті — Қазақстандағы ең көне жеке университеттердің бірі, бағдарламалардың кең спектрімен.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    directions: ['Бизнес', 'IT', 'Право', 'Туризм', 'Журналистика'],
    costRange: '1 000 000 – 1 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Дистанционная',
    website: 'https://turan-edu.kz',
    instagram: 'https://instagram.com/turan_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@turan-edu.kz',
    phone: '+7 (727) 250-24-44',
    tags: ['business', 'it', 'law', 'bachelor', 'master'],
    minEnt: 50,
  ),
  University(
    id: 'kazguu',
    name: LocalizedString(
      ru: 'Казахский гуманитарно-юридический университет',
      en: 'Kazakh Humanitarian Law University',
      kk: 'Қазақ гуманитарлық-заң университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КазГЮУ — ведущий юридический университет Казахстана. Есть государственные гранты.',
      en: 'KazGUU is Kazakhstan\'s leading law university. State grants available.',
      kk: 'ҚазГЗУ — Қазақстанның жетекші заң университеті. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Право', 'Государственное управление', 'Международные отношения'],
    costRange: 'Грант / до 1 600 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazguu.kz',
    instagram: 'https://instagram.com/kazguu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazguu.kz',
    phone: '+7 (727) 292-09-60',
    tags: ['law', 'grants', 'bachelor', 'master'],
    minEnt: 65,
  ),
  University(
    id: 'kau',
    name: LocalizedString(
      ru: 'Казахская академия транспорта и коммуникаций им. М. Тынышпаева',
      en: 'M. Tynyshpayev Kazakhstan Academy of Transport and Communications',
      kk: 'М. Тынышпаев атындағы Қазақ көлік және коммуникациялар академиясы',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КазАТК — ведущий транспортный университет Казахстана. Готовит инженеров для железнодорожной, авиационной и логистической отраслей. Есть государственные гранты.',
      en: 'KazATK is Kazakhstan\'s leading transport university. Trains engineers for rail, aviation and logistics industries. State grants available.',
      kk: 'ҚазАТК — Қазақстанның жетекші көлік университеті. Теміржол, авиация және логистика салаларына инженерлер дайындайды. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Инженерия', 'Транспорт', 'Логистика', 'IT'],
    costRange: 'Грант / до 1 500 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazatk.kz',
    instagram: 'https://instagram.com/kazatk_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazatk.kz',
    phone: '+7 (727) 292-27-92',
    tags: ['engineering', 'it', 'grants', 'bachelor', 'master'],
    minEnt: 55,
  ),
  University(
    id: 'kafu',
    name: LocalizedString(
      ru: 'Казахстанско-Американский свободный университет',
      en: 'Kazakhstan-American Free University',
      kk: 'Қазақстан-Американ еркін университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КАФУ — частный университет с американской моделью образования. Обучение на английском и русском языках.',
      en: 'KAFU is a private university with the American model of education. Instruction in English and Russian.',
      kk: 'ҚАФУ — американдық білім моделі бар жеке университет. Ағылшын және орыс тілдерінде оқыту.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Бизнес', 'IT', 'Право', 'Психология'],
    costRange: '1 100 000 – 2 000 000 ₸/год',
    duration: '4 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная, Гибридная',
    website: 'https://kafu.kz',
    instagram: 'https://instagram.com/kafu_almaty',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kafu.kz',
    phone: '+7 (727) 270-02-70',
    tags: ['business', 'it', 'law', 'bachelor', 'master'],
    minEnt: 55,
    minIelts: 5.0,
  ),
  University(
    id: 'kazart',
    name: LocalizedString(
      ru: 'Казахская национальная академия искусств им. Т. Жургенова',
      en: 'T. Zhurgenov Kazakh National Academy of Arts',
      kk: 'Т. Жүргенов атындағы Қазақ ұлттық өнер академиясы',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КазНАИ — главный творческий вуз Казахстана. Готовит специалистов в области театра, кино, дизайна, живописи и музыки. Есть государственные гранты.',
      en: 'KazNAI is Kazakhstan\'s main creative university. Trains specialists in theatre, cinema, design, painting and music. State grants available.',
      kk: 'ҚазҰӨА — Қазақстанның басты шығармашылық жоғары оқу орны. Театр, кино, дизайн, кескіндеме және музыка мамандарын дайындайды. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Дизайн', 'Кино и театр', 'Живопись', 'Музыка'],
    costRange: 'Грант / до 1 500 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazart.kz',
    instagram: 'https://instagram.com/zhurgenov_academy',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazart.kz',
    phone: '+7 (727) 267-08-08',
    tags: ['design', 'grants', 'bachelor', 'master'],
    minEnt: 55,
  ),
  University(
    id: 'almau',
    name: LocalizedString(
      ru: 'Алматы Менеджмент Университет (AlmaU)',
      en: 'Almaty Management University (AlmaU)',
      kk: 'Алматы менеджмент университеті (AlmaU)',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'AlmaU — ведущая бизнес-школа Казахстана, аккредитована AMBA. Специализируется на менеджменте, маркетинге, финансах и предпринимательстве.',
      en: 'AlmaU is Kazakhstan\'s leading business school, AMBA accredited. Specializes in management, marketing, finance and entrepreneurship.',
      kk: 'AlmaU — AMBA аккредитациясы бар Қазақстанның жетекші бизнес-мектебі. Менеджмент, маркетинг, қаржы және кәсіпкерлікке маманданған.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура, MBA',
    directions: ['Бизнес', 'Финансы', 'Маркетинг', 'Предпринимательство'],
    costRange: '1 800 000 – 3 200 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Гибридная',
    website: 'https://almau.edu.kz',
    instagram: 'https://instagram.com/almau_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@almau.edu.kz',
    phone: '+7 (727) 399-03-33',
    tags: ['business', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'kazeconomics',
    name: LocalizedString(
      ru: 'Казахский экономический университет им. Т. Рыскулова',
      en: 'T. Ryskulov Kazakh University of Economics',
      kk: 'Т. Рысқұлов атындағы Қазақ экономика университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КазЭУ — ведущий экономический университет Казахстана. Есть государственные гранты.',
      en: 'KazEU is Kazakhstan\'s leading economics university. State grants available.',
      kk: 'ҚазЭУ — Қазақстанның жетекші экономика университеті. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    directions: ['Бизнес', 'Экономика', 'Финансы', 'Статистика', 'IT'],
    costRange: 'Грант / до 1 600 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная, Дистанционная',
    website: 'https://kazeu.kz',
    instagram: 'https://instagram.com/kazeu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazeu.kz',
    phone: '+7 (727) 309-55-55',
    tags: ['business', 'it', 'grants', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'satpaev',
    name: LocalizedString(
      ru: 'Satbayev University',
      en: 'Satbayev University',
      kk: 'Сәтбаев Университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Казахский национальный исследовательский технический университет им. К. И. Сатпаева — ведущий технический вуз Казахстана. Есть государственные гранты.',
      en: 'Satbayev University is Kazakhstan\'s leading technical university. State grants available.',
      kk: 'Сәтбаев Университеті — Қазақстанның жетекші техникалық жоғары оқу орны. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    directions: ['Инженерия', 'Горное дело', 'Нефтегазовая отрасль', 'IT', 'Архитектура'],
    costRange: 'Грант / до 1 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная',
    website: 'https://satbayev.university',
    instagram: 'https://instagram.com/satbayev_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@satbayev.university',
    phone: '+7 (727) 320-55-55',
    tags: ['engineering', 'it', 'grants', 'bachelor', 'master'],
    minEnt: 65,
  ),
  University(
    id: 'kazakh_american',
    name: LocalizedString(
      ru: 'Казахстанско-Американский университет',
      en: 'Kazakhstan-American University',
      kk: 'Қазақстан-Американ университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КАУ — частный университет с американской моделью либерального образования. Сильные программы по IT, дизайну и бизнесу на английском языке.',
      en: 'KAU is a private university with the American liberal education model. Strong IT, design and business programs in English.',
      kk: 'ҚАУ — американдық либералды білім моделі бар жеке университет. IT, дизайн және бизнес бойынша күшті ағылшын тіліндегі бағдарламалар.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    directions: ['IT', 'Дизайн', 'Бизнес', 'Гуманитарные науки'],
    costRange: '1 200 000 – 2 100 000 ₸/год',
    duration: '4 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная',
    website: 'https://kau.edu.kz',
    instagram: 'https://instagram.com/kau_almaty',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kau.edu.kz',
    phone: '+7 (727) 233-88-88',
    tags: ['it', 'design', 'business', 'bachelor', 'master'],
    minEnt: 55,
    minIelts: 5.0,
  ),
  University(
    id: 'kazinfra',
    name: LocalizedString(
      ru: 'Казахская головная архитектурно-строительная академия',
      en: 'Kazakh Leading Architecture and Civil Engineering Academy',
      kk: 'Қазақ бас сәулет-құрылыс академиясы',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'КазГАСА — единственный в Казахстане профильный архитектурно-строительный вуз. Есть государственные гранты.',
      en: 'KazGASA is Kazakhstan\'s only specialized architecture and construction university. State grants available.',
      kk: 'ҚазБСА — Қазақстандағы жалғыз мамандандырылған сәулет-құрылыс жоғары оқу орны. Мемлекеттік гранттар бар.',
    ),
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Архитектура', 'Строительство', 'Дизайн', 'Инженерия'],
    costRange: 'Грант / до 1 500 000 ₸/год',
    duration: '4–5 лет',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazgasa.kz',
    instagram: 'https://instagram.com/kazgasa_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazgasa.kz',
    phone: '+7 (727) 309-67-89',
    tags: ['design', 'engineering', 'grants', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'kazmira',
    name: LocalizedString(
      ru: 'Университет «Мирас»',
      en: 'Miras University',
      kk: '«Мирас» Университеті',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Университет «Мирас» — многопрофильный частный вуз с широким спектром специальностей. Доступная стоимость обучения.',
      en: 'Miras University is a multidisciplinary private university with a wide range of majors. Affordable tuition.',
      kk: '«Мирас» университеті — мамандықтардың кең спектрі бар көпсалалы жеке жоғары оқу орны. Қолжетімді оқу бағасы.',
    ),
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    directions: ['Бизнес', 'Право', 'Педагогика', 'Инженерия', 'IT'],
    costRange: '900 000 – 1 500 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная, Дистанционная',
    website: 'https://miras.edu.kz',
    instagram: 'https://instagram.com/miras_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@miras.edu.kz',
    phone: '+7 (727) 394-80-80',
    tags: ['business', 'law', 'pedagogy', 'engineering', 'it', 'bachelor', 'master'],
    minEnt: 50,
  ),
  University(
    id: 'kazpharm',
    name: LocalizedString(
      ru: 'Казахстанский медицинский университет «Высшая школа общественного здравоохранения»',
      en: 'Kazakhstan Medical University "School of Public Health"',
      kk: 'Қазақстан медицина университеті «Қоғамдық денсаулық сақтау жоғары мектебі»',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'ВШОЗ — специализированный медицинский университет для подготовки управленцев в сфере здравоохранения. Программы на английском языке.',
      en: 'KSPH is a specialized medical university for training healthcare managers. English-language programs.',
      kk: 'ҚДСЖМ — денсаулық сақтау менеджерлерін даярлауға арналған мамандандырылған медицина университеті. Ағылшын тіліндегі бағдарламалар.',
    ),
    type: 'Частный',
    level: 'Магистратура, Докторантура',
    directions: ['Медицина', 'Общественное здравоохранение', 'Менеджмент в медицине'],
    costRange: '2 500 000 – 4 000 000 ₸/год',
    duration: '2 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная',
    website: 'https://ksph.kz',
    instagram: 'https://instagram.com/ksph_kz',
    imageUrl: '',
    logoUrl: '',
    email: 'info@ksph.kz',
    phone: '+7 (727) 279-06-49',
    tags: ['medicine', 'master'],
    minIelts: 6.0,
  ),
];

/// Колледжи и программы магистратуры.
const List<University> kSeedExtra = [
  University(
    id: 'col_kazgorizont',
    name: LocalizedString(
      ru: 'Казахский гуманитарно-технический колледж «Горизонт»',
      en: 'Kazakh Humanitarian and Technical College "Gorizont"',
      kk: '«Горизонт» қазақ гуманитарлық-техникалық колледжі',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Колледж «Горизонт» — один из крупнейших частных колледжей Алматы. Подготовка специалистов по IT, бизнесу, дизайну и педагогике.',
      en: 'Gorizont College is one of the largest private colleges in Almaty. Trains specialists in IT, business, design and pedagogy.',
      kk: '«Горизонт» колледжі — Алматының ірі жеке колледждерінің бірі. IT, бизнес, дизайн және педагогика мамандарын дайындайды.',
    ),
    type: 'Частный',
    level: 'Колледж',
    directions: ['IT', 'Бизнес', 'Дизайн', 'Педагогика'],
    costRange: '350 000 – 650 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 394-55-55',
    tags: ['it', 'business', 'design', 'pedagogy', 'college'],
  ),
  University(
    id: 'col_binom',
    name: LocalizedString(
      ru: 'Колледж информационных технологий «Бином»',
      en: 'Information Technology College "Binom"',
      kk: '«Бином» ақпараттық технологиялар колледжі',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Колледж «Бином» специализируется на подготовке IT-специалистов: программистов, системных администраторов и специалистов по кибербезопасности.',
      en: 'Binom College specializes in IT specialists: programmers, system administrators and cybersecurity professionals.',
      kk: '«Бином» колледжі IT мамандарын дайындауға маманданған: бағдарламашылар, жүйелік әкімшілер және киберқауіпсіздік мамандары.',
    ),
    type: 'Частный',
    level: 'Колледж',
    directions: ['IT'],
    costRange: '400 000 – 700 000 ₸/год',
    duration: '3 года',
    languages: ['Русский', 'Казахский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 312-44-44',
    tags: ['it', 'engineering', 'college'],
  ),
  University(
    id: 'mba_almau',
    name: LocalizedString(
      ru: 'AlmaU MBA',
      en: 'AlmaU MBA',
      kk: 'AlmaU MBA',
    ),
    city: LocalizedString(ru: 'Алматы', en: 'Almaty', kk: 'Алматы'),
    description: LocalizedString(
      ru: 'Программа MBA Алматы Менеджмент Университета — аккредитована AMBA. Специализации: General Management, Marketing, Finance.',
      en: 'AlmaU MBA program — AMBA accredited. Specializations: General Management, Marketing, Finance.',
      kk: 'AlmaU MBA бағдарламасы — AMBA аккредитациясы бар. Мамандануы: General Management, Marketing, Finance.',
    ),
    type: 'Частный',
    level: 'Магистратура (MBA)',
    directions: ['Бизнес', 'Финансы', 'Маркетинг'],
    costRange: '3 500 000 – 5 000 000 ₸/год',
    duration: '2 года',
    languages: ['Русский', 'Английский'],
    format: 'Гибридная',
    website: 'https://almau.edu.kz/mba',
    instagram: 'https://instagram.com/almau_official',
    imageUrl: '',
    logoUrl: '',
    email: 'mba@almau.edu.kz',
    phone: '+7 (727) 399-03-33',
    tags: ['business', 'master'],
    minIelts: 5.5,
  ),
];