import 'package:stiky/data/university/university_model.dart';

/// 20 учебных заведений Алматы для заливки в Firestore.
///
/// Залить один раз:
/// ```dart
/// await context.read<UniversityRepository>().seedAll(kSeedUniversities);
/// ```
/// После успешной заливки убрать вызов из кода.
const List<University> kSeedUniversities = [
  University(
    id: 'kimep',
    name: 'KIMEP University',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    description:
        'KIMEP University — один из ведущих частных университетов Казахстана с обучением на английском языке. '
        'Специализируется на бизнесе, праве и социальных науках. Аккредитован AACSB.',
    directions: ['Бизнес', 'Право', 'Социальные науки', 'Медиа'],
    costRange: '2 800 000 – 3 800 000 ₸/год',
    duration: '4 года',
    languages: ['Английский'],
    format: 'Очная',
    website: 'https://www.kimep.kz',
    instagram: 'https://instagram.com/kimepuniversity',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kimep.kz',
    phone: '+7 727 270 42 13',
    tags: ['business', 'law', 'bachelor', 'master'],
    minEnt: 80,
    minIelts: 6.0,
  ),
  University(
    id: 'kbtu',
    name: 'Казахстанско-Британский технический университет',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    description:
        'КБТУ — ведущий технический университет с совместными программами британских вузов. '
        'Сильные направления: нефтегазовая инженерия, IT, бизнес.',
    directions: ['IT', 'Инженерия', 'Нефтегазовая отрасль', 'Бизнес'],
    costRange: '2 200 000 – 3 500 000 ₸/год',
    duration: '4 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная',
    website: 'https://kbtu.kz',
    instagram: 'https://instagram.com/kbtu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kbtu.kz',
    phone: '+7 (727) 272-42-93',
    tags: ['it', 'engineering', 'business', 'bachelor', 'master'],
    minEnt: 70,
    minIelts: 5.5,
  ),
  University(
    id: 'kaznu',
    name: 'Казахский национальный университет им. аль-Фараби',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    description:
        'КазНУ — крупнейший и старейший университет Казахстана. '
        'Более 100 специальностей: гуманитарные, технические и естественно-научные направления. '
        'Есть бюджетные места по государственному гранту.',
    directions: ['IT', 'Медицина', 'Право', 'Бизнес', 'Инженерия', 'Гуманитарные науки', 'Естественные науки'],
    costRange: 'Грант / до 1 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Дистанционная',
    website: 'https://kaznu.kz',
    instagram: 'https://instagram.com/kaznu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'priem@kaznu.kz',
    phone: '+7 (727) 377-33-33',
    tags: ['it', 'medicine', 'law', 'business', 'engineering', 'grants', 'bachelor', 'master'],
    minEnt: 65,
  ),
  University(
    id: 'iitu',
    name: 'Международный университет информационных технологий',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    description:
        'МУИТ — ведущий IT-университет Казахстана. Готовит специалистов '
        'в области программной инженерии, кибербезопасности и искусственного интеллекта. '
        'Есть государственные гранты.',
    directions: ['IT'],
    costRange: 'Грант / до 1 600 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная',
    website: 'https://iitu.edu.kz',
    instagram: 'https://instagram.com/iitu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@iitu.edu.kz',
    phone: '+7 (727) 355-34-00',
    tags: ['it', 'engineering', 'grants', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'narxoz',
    name: 'Университет Нархоз',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    description:
        'Нархоз — ведущий частный университет в области экономики и бизнеса. '
        'Международные аккредитации, партнёрство с European Business School.',
    directions: ['Бизнес', 'Право', 'Экономика', 'IT', 'Финансы'],
    costRange: '1 500 000 – 2 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Дистанционная',
    website: 'https://narxoz.kz',
    instagram: 'https://instagram.com/narxoz_university',
    imageUrl: '',
    logoUrl: '',
    email: 'admissions@narxoz.kz',
    phone: '+7 (727) 377-11-11',
    tags: ['business', 'law', 'it', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'kaznpu',
    name: 'КазНПУ им. Абая',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    description:
        'Казахский национальный педагогический университет им. Абая — '
        'главный педагогический вуз Казахстана. Готовит учителей, психологов '
        'и специалистов в области образования. Есть государственные гранты.',
    directions: ['Педагогика', 'Психология', 'Гуманитарные науки', 'Естественные науки', 'IT'],
    costRange: 'Грант / до 1 200 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная, Дистанционная',
    website: 'https://kaznpu.kz',
    instagram: 'https://instagram.com/kaznpu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kaznpu.kz',
    phone: '+7 (727) 291-91-91',
    tags: ['pedagogy', 'grants', 'bachelor', 'master'],
    minEnt: 55,
  ),
  University(
    id: 'kazmed',
    name: 'КазНМУ им. С. Д. Асфендиярова',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Резидентура',
    description:
        'Казахский национальный медицинский университет — ведущий медицинский вуз Казахстана. '
        'Готовит врачей, фармацевтов и специалистов общественного здравоохранения. '
        'Есть государственные гранты.',
    directions: ['Медицина', 'Фармацевтика', 'Стоматология', 'Общественное здравоохранение'],
    costRange: 'Грант / до 2 000 000 ₸/год',
    duration: '5–6 лет',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная',
    website: 'https://kaznmu.kz',
    instagram: 'https://instagram.com/kaznmu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kaznmu.kz',
    phone: '+7 (727) 292-06-30',
    tags: ['medicine', 'grants', 'bachelor', 'master'],
    minEnt: 70,
  ),
  University(
    id: 'alma_u',
    name: 'Alma University',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    description:
        'Alma University — современный частный университет с фокусом на бизнес, '
        'право и цифровые технологии. Практикоориентированный подход и активное '
        'сотрудничество с работодателями.',
    directions: ['Бизнес', 'Право', 'IT', 'Дизайн'],
    costRange: '1 300 000 – 2 200 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Гибридная',
    website: 'https://alma.edu.kz',
    instagram: 'https://instagram.com/alma_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@alma.edu.kz',
    phone: '+7 (727) 311-11-40',
    tags: ['business', 'law', 'it', 'design', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'turan',
    name: 'Университет Туран',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    description:
        'Университет Туран — один из старейших частных университетов Казахстана. '
        'Широкий спектр направлений: экономика, IT, право, туризм и журналистика.',
    directions: ['Бизнес', 'IT', 'Право', 'Туризм', 'Журналистика'],
    costRange: '1 000 000 – 1 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Дистанционная',
    website: 'https://turan-edu.kz',
    instagram: 'https://instagram.com/turan_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@turan-edu.kz',
    phone: '+7 (727) 250-24-44',
    tags: ['business', 'it', 'law', 'bachelor', 'master'],
    minEnt: 50,
  ),
  University(
    id: 'kazguu',
    name: 'Казахский гуманитарно-юридический университет',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    description:
        'КазГЮУ — ведущий юридический университет Казахстана. '
        'Готовит юристов, специалистов в области права и государственного управления. '
        'Есть государственные гранты.',
    directions: ['Право', 'Государственное управление', 'Международные отношения'],
    costRange: 'Грант / до 1 600 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazguu.kz',
    instagram: 'https://instagram.com/kazguu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazguu.kz',
    phone: '+7 (727) 292-09-60',
    tags: ['law', 'grants', 'bachelor', 'master'],
    minEnt: 65,
  ),
  University(
    id: 'kau',
    name: 'Казахская академия транспорта и коммуникаций им. М. Тынышпаева',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    description:
        'КазАТК — ведущий транспортный университет Казахстана. '
        'Готовит инженеров для железнодорожной, авиационной и логистической отраслей. '
        'Есть государственные гранты.',
    directions: ['Инженерия', 'Транспорт', 'Логистика', 'IT'],
    costRange: 'Грант / до 1 500 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazatk.kz',
    instagram: 'https://instagram.com/kazatk_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazatk.kz',
    phone: '+7 (727) 292-27-92',
    tags: ['engineering', 'it', 'grants', 'bachelor', 'master'],
    minEnt: 55,
  ),
  University(
    id: 'kafu',
    name: 'Казахстанско-Американский свободный университет',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    description:
        'КАФУ — частный университет с американской моделью образования. '
        'Обучение на английском и русском языках. '
        'Специализируется на бизнесе, IT и социальных науках.',
    directions: ['Бизнес', 'IT', 'Право', 'Психология'],
    costRange: '1 100 000 – 2 000 000 ₸/год',
    duration: '4 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная, Гибридная',
    website: 'https://kafu.kz',
    instagram: 'https://instagram.com/kafu_almaty',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kafu.kz',
    phone: '+7 (727) 270-02-70',
    tags: ['business', 'it', 'law', 'bachelor', 'master'],
    minEnt: 55,
    minIelts: 5.0,
  ),
  University(
    id: 'kazart',
    name: 'Казахская национальная академия искусств им. Т. Жургенова',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    description:
        'КазНАИ — главный творческий вуз Казахстана. '
        'Готовит специалистов в области театра, кино, дизайна, живописи и музыки. '
        'Есть государственные гранты.',
    directions: ['Дизайн', 'Кино и театр', 'Живопись', 'Музыка'],
    costRange: 'Грант / до 1 500 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazart.kz',
    instagram: 'https://instagram.com/zhurgenov_academy',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazart.kz',
    phone: '+7 (727) 267-08-08',
    tags: ['design', 'grants', 'bachelor', 'master'],
    minEnt: 55,
  ),
  University(
    id: 'almau',
    name: 'Алматы Менеджмент Университет (AlmaU)',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура, MBA',
    description:
        'AlmaU — ведущая бизнес-школа Казахстана, аккредитована AMBA. '
        'Специализируется на менеджменте, маркетинге, финансах и предпринимательстве. '
        'Сильная программа MBA.',
    directions: ['Бизнес', 'Финансы', 'Маркетинг', 'Предпринимательство'],
    costRange: '1 800 000 – 3 200 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Гибридная',
    website: 'https://almau.edu.kz',
    instagram: 'https://instagram.com/almau_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@almau.edu.kz',
    phone: '+7 (727) 399-03-33',
    tags: ['business', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'kazeconomics',
    name: 'Казахский экономический университет им. Т. Рыскулова',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    description:
        'КазЭУ — ведущий экономический университет Казахстана. '
        'Готовит специалистов в области экономики, финансов, учёта и статистики. '
        'Есть государственные гранты.',
    directions: ['Бизнес', 'Экономика', 'Финансы', 'Статистика', 'IT'],
    costRange: 'Грант / до 1 600 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная, Дистанционная',
    website: 'https://kazeu.kz',
    instagram: 'https://instagram.com/kazeu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazeu.kz',
    phone: '+7 (727) 309-55-55',
    tags: ['business', 'it', 'grants', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'satpaev',
    name: 'Satbayev University',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура, Докторантура',
    description:
        'Казахский национальный исследовательский технический университет им. К. И. Сатпаева — '
        'ведущий технический вуз Казахстана. Готовит инженеров для горнодобывающей, '
        'нефтегазовой, строительной и IT-отраслей. Есть государственные гранты.',
    directions: ['Инженерия', 'Горное дело', 'Нефтегазовая отрасль', 'IT', 'Архитектура'],
    costRange: 'Грант / до 1 800 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная',
    website: 'https://satbayev.university',
    instagram: 'https://instagram.com/satbayev_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@satbayev.university',
    phone: '+7 (727) 320-55-55',
    tags: ['engineering', 'it', 'grants', 'bachelor', 'master'],
    minEnt: 65,
  ),
  University(
    id: 'kazakh_american',
    name: 'Казахстанско-Американский университет',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    description:
        'КАУ — частный университет с американской моделью либерального образования. '
        'Сильные программы по IT, дизайну и бизнесу на английском языке.',
    directions: ['IT', 'Дизайн', 'Бизнес', 'Гуманитарные науки'],
    costRange: '1 200 000 – 2 100 000 ₸/год',
    duration: '4 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная',
    website: 'https://kau.edu.kz',
    instagram: 'https://instagram.com/kau_almaty',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kau.edu.kz',
    phone: '+7 (727) 233-88-88',
    tags: ['it', 'design', 'business', 'bachelor', 'master'],
    minEnt: 55,
    minIelts: 5.0,
  ),
  University(
    id: 'kazinfra',
    name: 'Казахская головная архитектурно-строительная академия',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Бакалавриат, Магистратура',
    description:
        'КазГАСА — единственный в Казахстане профильный архитектурно-строительный вуз. '
        'Готовит архитекторов, строителей и дизайнеров среды. Есть государственные гранты.',
    directions: ['Архитектура', 'Строительство', 'Дизайн', 'Инженерия'],
    costRange: 'Грант / до 1 500 000 ₸/год',
    duration: '4–5 лет',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: 'https://kazgasa.kz',
    instagram: 'https://instagram.com/kazgasa_official',
    imageUrl: '',
    logoUrl: '',
    email: 'info@kazgasa.kz',
    phone: '+7 (727) 309-67-89',
    tags: ['design', 'engineering', 'grants', 'bachelor', 'master'],
    minEnt: 60,
  ),
  University(
    id: 'kazmira',
    name: 'Университет «Мирас»',
    city: 'Алматы',
    type: 'Частный',
    level: 'Бакалавриат, Магистратура',
    description:
        'Университет «Мирас» — многопрофильный частный вуз с широким спектром '
        'специальностей в области экономики, права, педагогики и технических наук. '
        'Доступная стоимость обучения.',
    directions: ['Бизнес', 'Право', 'Педагогика', 'Инженерия', 'IT'],
    costRange: '900 000 – 1 500 000 ₸/год',
    duration: '4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная, Дистанционная',
    website: 'https://miras.edu.kz',
    instagram: 'https://instagram.com/miras_university',
    imageUrl: '',
    logoUrl: '',
    email: 'info@miras.edu.kz',
    phone: '+7 (727) 394-80-80',
    tags: ['business', 'law', 'pedagogy', 'engineering', 'it', 'bachelor', 'master'],
    minEnt: 50,
  ),
  University(
    id: 'kazpharm',
    name: 'Казахстанский медицинский университет «Высшая школа общественного здравоохранения»',
    city: 'Алматы',
    type: 'Частный',
    level: 'Магистратура, Докторантура',
    description:
        'ВШОЗ — специализированный медицинский университет для подготовки '
        'управленцев в сфере здравоохранения. Программы на английском языке, '
        'партнёрство с американскими университетами.',
    directions: ['Медицина', 'Общественное здравоохранение', 'Менеджмент в медицине'],
    costRange: '2 500 000 – 4 000 000 ₸/год',
    duration: '2 года',
    languages: ['Английский', 'Русский'],
    format: 'Очная',
    website: 'https://ksph.kz',
    instagram: 'https://instagram.com/ksph_kz',
    imageUrl: '',
    logoUrl: '',
    email: 'info@ksph.kz',
    phone: '+7 (727) 279-06-49',
    tags: ['medicine', 'master'],
    minIelts: 6.0,
  ),
];

/// Дополнительные учебные заведения для дозаливки в Firestore.
///
/// Использовать ОТДЕЛЬНО от первого seed — эти записи добавляются поверх
/// уже залитых 20 университетов:
/// ```dart
/// await context.read<UniversityRepository>().seedAll(kSeedExtra);
/// ```
const List<University> kSeedExtra = [
  // ────────────────────────────────────────────────────────────────────────────
  // КОЛЛЕДЖИ (10)
  // ────────────────────────────────────────────────────────────────────────────

  University(
    id: 'col_kazgorizont',
    name: 'Казахский гуманитарно-технический колледж «Горизонт»',
    city: 'Алматы',
    type: 'Частный',
    level: 'Колледж',
    description:
        'Колледж «Горизонт» — один из крупнейших частных колледжей Алматы. '
        'Подготовка специалистов среднего звена по IT, бизнесу, дизайну и '
        'педагогике. Современная материально-техническая база.',
    directions: ['IT', 'Бизнес', 'Дизайн', 'Педагогика'],
    costRange: '350 000 – 650 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 394-55-55',
    tags: ['it', 'business', 'design', 'pedagogy', 'college'],
  ),
  University(
    id: 'col_binom',
    name: 'Колледж информационных технологий «Бином»',
    city: 'Алматы',
    type: 'Частный',
    level: 'Колледж',
    description:
        'Колледж «Бином» специализируется на подготовке IT-специалистов: '
        'программистов, системных администраторов и специалистов '
        'по кибербезопасности. Дуальное обучение с работодателями.',
    directions: ['IT'],
    costRange: '400 000 – 700 000 ₸/год',
    duration: '3 года',
    languages: ['Русский', 'Казахский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 312-44-44',
    tags: ['it', 'engineering', 'college'],
  ),
  University(
    id: 'col_medbusiness',
    name: 'Алматинский медицинский колледж',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Колледж',
    description:
        'Ведущий государственный медицинский колледж Алматы. Готовит фельдшеров, '
        'медсестёр, фармацевтов и лаборантов. Есть бюджетные места по гранту.',
    directions: ['Медицина', 'Фармацевтика'],
    costRange: 'Грант / до 450 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 292-11-22',
    tags: ['medicine', 'grants', 'college'],
  ),
  University(
    id: 'col_finance',
    name: 'Алматинский колледж экономики и статистики',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Колледж',
    description:
        'Специализированный колледж по подготовке бухгалтеров, экономистов '
        'и специалистов по статистике. Один из старейших экономических '
        'колледжей Казахстана. Есть государственные гранты.',
    directions: ['Бизнес', 'Финансы', 'Экономика'],
    costRange: 'Грант / до 380 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 309-22-11',
    tags: ['business', 'grants', 'college'],
  ),
  University(
    id: 'col_law',
    name: 'Алматинский юридический колледж',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Колледж',
    description:
        'Профильный юридический колледж, готовящий помощников юриста, '
        'специалистов по правоохранительной деятельности и нотариату. '
        'Есть государственные гранты.',
    directions: ['Право'],
    costRange: 'Грант / до 360 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 292-33-44',
    tags: ['law', 'grants', 'college'],
  ),
  University(
    id: 'col_design',
    name: 'Алматинский колледж дизайна и технологий',
    city: 'Алматы',
    type: 'Частный',
    level: 'Колледж',
    description:
        'Творческий колледж с углублённым изучением графического дизайна, '
        'fashion-дизайна, интерьера и мультимедиа. Современные мастерские '
        'и активное сотрудничество с дизайн-студиями.',
    directions: ['Дизайн'],
    costRange: '500 000 – 800 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 267-55-66',
    tags: ['design', 'college'],
  ),
  University(
    id: 'col_poly',
    name: 'Алматинский политехнический колледж',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Колледж',
    description:
        'Политехнический колледж с широким выбором технических специальностей: '
        'электротехника, сварочное дело, строительство и автоматизация. '
        'Есть государственные гранты. Дуальное обучение.',
    directions: ['Инженерия', 'Строительство', 'Электротехника'],
    costRange: 'Грант / до 400 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 320-11-22',
    tags: ['engineering', 'grants', 'college'],
  ),
  University(
    id: 'col_tourism',
    name: 'Алматинский колледж туризма и сервиса',
    city: 'Алматы',
    type: 'Частный',
    level: 'Колледж',
    description:
        'Профильный колледж по подготовке специалистов в сфере туризма, '
        'гостиничного бизнеса и ресторанного дела. Практика в ведущих '
        'отелях и туроператорах Алматы.',
    directions: ['Туризм', 'Бизнес'],
    costRange: '380 000 – 580 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 250-77-88',
    tags: ['business', 'college'],
  ),
  University(
    id: 'col_ped',
    name: 'Алматинский педагогический колледж',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Колледж',
    description:
        'Педагогический колледж готовит воспитателей детских садов, '
        'учителей начальных классов и учителей физкультуры. '
        'Есть государственные гранты. Педагогическая практика в школах.',
    directions: ['Педагогика'],
    costRange: 'Грант / до 350 000 ₸/год',
    duration: '3 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 291-44-55',
    tags: ['pedagogy', 'grants', 'college'],
  ),
  University(
    id: 'col_music',
    name: 'Алматинский колледж искусств им. А. Жубанова',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Колледж',
    description:
        'Профессиональный колледж искусств, готовящий музыкантов, '
        'хореографов и артистов. Один из старейших творческих колледжей '
        'Казахстана. Есть государственные гранты.',
    directions: ['Дизайн', 'Музыка', 'Хореография'],
    costRange: 'Грант / до 400 000 ₸/год',
    duration: '3–4 года',
    languages: ['Казахский', 'Русский'],
    format: 'Очная',
    website: '',
    instagram: '',
    imageUrl: '',
    logoUrl: '',
    email: '',
    phone: '+7 (727) 267-22-33',
    tags: ['design', 'grants', 'college'],
  ),

  // ────────────────────────────────────────────────────────────────────────────
  // МАГИСТРАТУРА (5)
  // ────────────────────────────────────────────────────────────────────────────

  University(
    id: 'mba_almau',
    name: 'AlmaU MBA',
    city: 'Алматы',
    type: 'Частный',
    level: 'Магистратура (MBA)',
    description:
        'Программа MBA Алматы Менеджмент Университета — аккредитована AMBA. '
        'Специализации: General Management, Marketing, Finance. '
        'Обучение в вечернем и weekend-формате для работающих специалистов.',
    directions: ['Бизнес', 'Финансы', 'Маркетинг'],
    costRange: '3 500 000 – 5 000 000 ₸/год',
    duration: '2 года',
    languages: ['Русский', 'Английский'],
    format: 'Гибридная',
    website: 'https://almau.edu.kz/mba',
    instagram: 'https://instagram.com/almau_official',
    imageUrl: '',
    logoUrl: '',
    email: 'mba@almau.edu.kz',
    phone: '+7 (727) 399-03-33',
    tags: ['business', 'master'],
    minIelts: 5.5,
  ),
  University(
    id: 'msc_nu',
    name: 'Назарбаев Университет — Магистратура',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Магистратура',
    description:
        'Программы магистратуры НУ реализуются совместно с партнёрскими '
        'университетами мирового уровня: Duke, UCL, Carnegie Mellon. '
        'Полное финансирование для лучших кандидатов. Обучение на английском.',
    directions: ['IT', 'Инженерия', 'Бизнес', 'Медицина', 'Социальные науки'],
    costRange: 'Грант / до 4 500 000 ₸/год',
    duration: '2 года',
    languages: ['Английский'],
    format: 'Очная',
    website: 'https://nu.edu.kz/admissions/graduate',
    instagram: 'https://instagram.com/nazarbayevuniversity',
    imageUrl: '',
    logoUrl: '',
    email: 'graduate@nu.edu.kz',
    phone: '+7 (7172) 70-66-88',
    tags: ['it', 'engineering', 'business', 'medicine', 'grants', 'master'],
    minIelts: 6.5,
    minGpa: 3.0,
  ),
  University(
    id: 'msc_kimep',
    name: 'KIMEP University — Магистратура',
    city: 'Алматы',
    type: 'Частный',
    level: 'Магистратура',
    description:
        'Программы MBA и MSc КИМЭП — одни из самых престижных в Казахстане. '
        'Специализации: Business Administration, Law, Social Sciences. '
        'Аккредитованы AACSB. Вечерний формат для работающих.',
    directions: ['Бизнес', 'Право', 'Социальные науки'],
    costRange: '3 200 000 – 4 200 000 ₸/год',
    duration: '2 года',
    languages: ['Английский'],
    format: 'Очная, Гибридная',
    website: 'https://kimep.kz/academics/graduate',
    instagram: 'https://instagram.com/kimepuniversity',
    imageUrl: '',
    logoUrl: '',
    email: 'graduate@kimep.kz',
    phone: '+7 727 270 42 13',
    tags: ['business', 'law', 'master'],
    minIelts: 6.0,
    minGpa: 2.75,
  ),
  University(
    id: 'msc_kaznu',
    name: 'КазНУ им. аль-Фараби — Магистратура',
    city: 'Алматы',
    type: 'Государственный',
    level: 'Магистратура',
    description:
        'Магистратура КазНУ — более 80 программ по всем направлениям: '
        'технические, гуманитарные, естественно-научные и педагогические. '
        'Есть государственные гранты. Научная и профильная магистратура.',
    directions: ['IT', 'Медицина', 'Право', 'Бизнес', 'Инженерия', 'Педагогика'],
    costRange: 'Грант / до 1 800 000 ₸/год',
    duration: '2 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная',
    website: 'https://kaznu.kz/magistratura',
    instagram: 'https://instagram.com/kaznu_official',
    imageUrl: '',
    logoUrl: '',
    email: 'magistr@kaznu.kz',
    phone: '+7 (727) 377-33-33',
    tags: ['it', 'medicine', 'law', 'business', 'engineering', 'pedagogy', 'grants', 'master'],
    minGpa: 2.5,
  ),
  University(
    id: 'msc_narxoz',
    name: 'Нархоз — Магистратура',
    city: 'Алматы',
    type: 'Частный',
    level: 'Магистратура',
    description:
        'Программы магистратуры Нархоз: MBA, MSc Finance, MSc Digital Business. '
        'Партнёрство с European Business School. Международная аккредитация. '
        'Вечерний формат — можно совмещать с работой.',
    directions: ['Бизнес', 'Финансы', 'IT', 'Право'],
    costRange: '2 500 000 – 3 800 000 ₸/год',
    duration: '2 года',
    languages: ['Казахский', 'Русский', 'Английский'],
    format: 'Очная, Гибридная',
    website: 'https://narxoz.kz/magistratura',
    instagram: 'https://instagram.com/narxoz_university',
    imageUrl: '',
    logoUrl: '',
    email: 'master@narxoz.kz',
    phone: '+7 (727) 377-11-11',
    tags: ['business', 'law', 'it', 'master'],
    minGpa: 2.5,
    minIelts: 5.0,
  ),
];